PADV-1357 feat: frontend - Create lab summary section 3r
Pearson-Advance/frontend-app-skillable pull request #10
Opened 2024-07-30 20:15 UTC by nandodev-net

## Tickets

- https://agile-jira.pearson.com/browse/PADV-1357

## Description
This PR adds the LabDetailsCard component to the LabDetails UI.

## Changes

- [x] Creates the LabDetailsCard component.
- [x] Adding Styles.
- [x] Create a formatTime() function to handle the datetime input format.
- [x] Adding the LabDetailsCard component to the LabDetails view and set the arguments.

## How To Test

- To properly test this, please go to the following URL: http://localhost:2002/skillable_plugin/course-tab/courses/[COURSE_ID]/training_labs where you have to set the COURSE_ID in the URL with a valid course id of your devstack installation. EG: course-v1:demo+demo1+2020 now it would show a table with the users enrolled to the course. Next click on any user that has a lab instance, and after click on an instance and you'll see the Lab Details View with the details card.

![image](https://github.com/user-attachments/assets/522824ef-2a31-437c-882e-ace85120b849)

2024-07-31 16:37 UTC, nandodev-net commented on src/components/LabDetails/index.jsx
> +    const options = {
@Nekenhei  You can nest N-functions in a line, but is it easy to read?

2024-07-31 16:53 UTC, nandodev-net commented on src/components/LabDetailsCard/index.jsx
> +import './index.scss'; // Aquí puedes añadir estilos personalizados si es necesario
This will be deleted...

2024-07-31 16:53 UTC, nandodev-net commented on src/components/LabDetailsCard/index.jsx
> +// src/components/LabDetailsCard/index.jsx
nope... deleted

2024-07-31 17:41 UTC, nandodev-net commented on src/components/LabDetailsCard/index.scss
> +    display: block;
nope... this happends whed you put the block on .lab-details-item 
![image](https://github.com/user-attachments/assets/433ef8e5-312b-4c77-a9a9-881e7e01eb2e)

2024-07-31 19:32 UTC, Nekenhei requested changes

2024-07-31 19:32 UTC, Nekenhei commented on src/components/LabDetails/index.jsx
> +          {/* Render the pie chart card. */}
```suggestion
          {/* Useful for further features. */}
```

Keep in mind that pie chart haven't been confirmed

2024-07-31 20:01 UTC, 01001110J approved these changes

2024-08-01 00:47 UTC, JuanDavidBuitrago approved these changes

2024-08-01 01:59 UTC, merged